### ISSUE TITLE
Including child collections

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/devonthink#2] opened 2019-07-15 10:42 UTC
Is it possible to include the designated collection and all child collections - and to place the articles in folders with the name of the parent collection?

**Comment by retorquere** [comment] 2019-07-15 23:12
This could be a duplicate of #4 -- please check.

**Comment by richardkaplan** [comment] 2019-07-15 23:30
What is not a duplicate is the part about placing the articles inside folders bearing the name of the article's immediate parent collection.   I guess we will not know for sure if that works until we figure out why it is not retrieving any of the articles in the subcollections.

It would be helpful as well if there were a top level folder just below the default "output" folder which has the title of the main parent collection.

**Comment by retorquere** [comment] 2019-07-15 23:45
Ah, like so. I'll have to think about this -- the CSL-JSON spec has no room for collection data.

**Comment by retorquere** [comment] 2019-07-15 23:46
Wait -- items can be in many collections so this could lead to duplicates being exported.

**Comment by richardkaplan** [comment] 2019-07-15 23:50
Duplicates like that  will not be a problem.  The duplicates will be in separate folders so it will not be a problem for OS X.  When Devonthink indexes them it will recognize the duplicates and mark them as such.  Not a problem for either of us to worry about.

If we can solve this and have the items placed in nested folders corresponding to the Zotero collections and subcollections then that will carry over very well to the Devonthink concept of Groups and will be supremely useful in Devonthink.

**Closed as completed** 2019-07-16 00:45 UTC

**Comment by retorquere** [comment] 2019-07-16 00:47
The format of the items has changed -- field names are now more directly like what they are in Zotero. Items will be exported according to their collection, with the behavior currently being that if an item is in any collection, it does not appear at the root.

The url ending has changed from `.csljson` to `.json`.
